title: mercator.calendar::lang.navigation.entries
modelClass: Mercator\Calendar\Models\CalendarEntry
list: $/mercator/calendar/models/calendarentry/columns.yaml
recordUrl: 'mercator/calendar/calendarentries/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
filter: config_filter.yaml # Add this line
defaultSort:  # Add this section
    column: event_date
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'

